nci: hack to fix terminal encoding issue
Apparently fb8b9161c7741183c74906b0ad185ec084c20f00 introduced a
problem for the nci.  The above added the following:

sys.stdout = codecs.getwriter('utf8')(sys.stdout)

This apparently breaks the nci when presumably? utf-8 character
decoding is attempted:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 63: ordinal not in range(128)

I most certainly understand what's going on here.  But storing the
original stdout method in the cli module, and then restoring it when
the nci is initiated seems to at least get around the problem.